# Generated by Django 4.2.18 on 2025-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocklyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the project', max_length=255)),
                ('description', models.TextField(help_text='Description of the project')),
                ('block_data', models.TextField(help_text='Serialized block data')),
                ('canvas_thumbnail', models.ImageField(help_text='Thumbnail of the canvas', upload_to='thumbnails/')),
                ('block_thumbnail', models.ImageField(help_text='Thumbnail of the blocks', upload_to='thumbnails/')),
                ('is_public', models.BooleanField(default=False, help_text='Is the project public?')),
            ],
            options={
                'verbose_name': 'Blockly Project',
                'verbose_name_plural': 'Blockly Projects',
            },
        ),
    ]
