# Generated by Django 4.2.18 on 2025-03-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockly', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklyproject',
            name='block_thumbnail_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded thumbnail of the blocks', null=True),
        ),
        migrations.AddField(
            model_name='blocklyproject',
            name='canvas_thumbnail_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded thumbnail of the canvas', null=True),
        ),
        migrations.AlterField(
            model_name='blocklyproject',
            name='block_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail of the blocks', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blocklyproject',
            name='canvas_thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail of the canvas', null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='blocklyproject',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the project', null=True),
        ),
    ]
