# Generated by Django 5.1.5 on 2026-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockly', '0003_blocklyproject_block_thumbnail_base64_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklyproject',
            name='watched_variables',
            field=models.TextField(default='[]', help_text='List of variables being watched'),
        ),
    ]
